on:
  workflow_dispatch:
  push:
    branches: [main]

name: CI

concurrency: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=raw,value={{date 'YYYY-MM-DDTHH:mm:ss' tz='Europe/Paris' }}
            type=ref,event=branch
                  - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

      - uses: "docker/login-action@v3"
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image with dependencies
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            push: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64

